server:
  port: 80 #http 默认端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true #开启自动路由
          lower-case-service-id: true # 将服务名小写

      #手动路由
#      routes:
#        - id: search-service-id #路由ID 不要重复
#          uri: lb://search-service
#          predicates:
#            - Path=/search/**




