server:
  port: 8082
spring:
  application:
    name: sentinel-clientB-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

