server:
  port: 8081
spring:
  application:
    name: alibaba-nacos-consumer
  cloud:
    nacos:
      server-addr: localhost:8848
      # 当注册中心和配置中心在一个nacos-server下，我们直接配置spring.cloud.nacos.username即可
      username: nacos
      password: nacos
