#docker eureka配置
#server:
#  port: ${PORT:8761}
#spring:
#  application:
#    name: eureka-server #应用名称
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#    fetch-registry: true
#    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
#  server:
#    eviction-interval-timer-in-ms: 90000
#  instance:
#    lease-expiration-duration-in-seconds: 90
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: ${APP_HOST:locahost}  #主机地址
#    prefer-ip-address: ${IP_ADDRESS:true}  #显示名称


#单机版配置
#端口号，eureka默认端口应当使用8761
server:
  port: 8761

#应用名称
spring:
  application:
    name: eureka-server
#eureka默认向localhost:8761注册自己
eureka:
  client:
    #表示注册中心的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #是否将自己注册到eureka中，eureka-server集群化配置需要开启此配置
    register-with-eureka: false
    #注册到注册中心之后，是否拉取服务列表，eureka-server集群化配置需要开启此配置
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 60000 #每隔60s执行清除任务：把无效的服务从服务列表中移除
    enable-self-preservation: true #server的自我保护机制，项目后一定要打开该配置
    renewal-percent-threshold: 0.85 #85%，如果在一个机房的client端，15分钟内有85%的client没有续约，那么则可能是网络原因，
                                    #认为服务实例没有问题，不会剔除他们，宁可放过一万，不可错杀一个，确保高可用
  instance:
    lease-renewal-interval-in-seconds: 30 #客户端多久向服务端发送一次心跳
    leaseExpirationDurationInSeconds: 90 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，
                                          #在这个时间内若没收到下一次心跳，则从服务列表中移除该实例

#集群版配置
#m1机器
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server #服务名称
#eureka:
#  client:
#    fetch-registry: true   #是否拉取服务列表
#    register-with-eureka: true     #是否注册自己（集群需要注册自己和拉取服务）
#    service-url:
#      defaultZone: http://m2:8762/eureka/,http://m3:8763/eureka/
#  server:
#    eviction-interval-timer-in-ms: 90000    #清除无效节点的评率(毫秒)
#  instance:
#    hostname: m1
#    lease-expiration-duration-in-seconds: 90    #server在等待下一个客户端发送的心跳时间，若在指定时间不能收到客户端心跳，则剔除此实例并且禁止流量

#m2机器
#server:
#  port: 8762
#spring:
#  application:
#    name: eureka-server #服务名称
#eureka:
#  client:
#    fetch-registry: true   #是否拉取服务列表
#    register-with-eureka: true     #是否注册自己（集群需要注册自己和拉取服务）
#    service-url:
#      defaultZone: http://m1:8761/eureka/,http://m3:8763/eureka/
#  server:
#    eviction-interval-timer-in-ms: 90000    #清除无效节点的评率(毫秒)
#  instance:
#    hostname: m2
#    lease-expiration-duration-in-seconds: 90    #server在等待下

#m3机器
#server:
#  port: 8763
#spring:
#  application:
#    name: eureka-server #服务名称
#eureka:
#  client:
#    fetch-registry: true   #是否拉取服务列表
#    register-with-eureka: true     #是否注册自己（集群需要注册自己和拉取服务）
#    service-url:
#      defaultZone: http://m1:8761/eureka/,http://m2:8762/eureka/
#  server:
#    eviction-interval-timer-in-ms: 90000    #清除无效节点的评率(毫秒)
#  instance:
#    hostname: m3
#    lease-expiration-duration-in-seconds: 90    #server在等待下
